#!/bin/bash

SCRIPT_PATH="$(dirname "$0")"
cd "$SCRIPT_PATH/.."

if [ ! -v PROJECT_BASE ]; then
	echo "PROJECT_BASE is not set"
	exit 1
fi

export build_dir="$PROJECT_BASE/build"
if [[ "$1" =~ ^(-c|--clear)$ ]]; then
	rm -rf "$build_dir" && mkdir -p "$build_dir"
fi

make build-x86_64
qemu-system-x86_64 -cdrom $build_dir/dist/x86_64/kernel.iso