#!/bin/bash

SCRIPT_PATH="$(dirname "$0")"
cd "$SCRIPT_PATH/../src"

if [ ! -v PROJECT_BASE ]; then
	echo "PROJECT_BASE is not set"
	exit 1
fi

build_dir="$PROJECT_BASE/build"
rm -rf "$build_dir" && mkdir -p "$build_dir"

nasm -f bin boot.asm -o "$build_dir/boot.bin"
qemu-system-x86_64 -drive file="$build_dir/boot.bin",format=raw
