#!/bin/bash -e

if [ ! -v PROJECT_BASE ] || [ ! -v PROJECT_NAME ]; then
	echo "Variables PROJECT_BASE and PROJECT_NAME need to be set"
fi

cd $PROJECT_BASE/$PROJECT_NAME && pwd

git fetch
ACTIVE_BRANCH=$(git rev-parse --abbrev-ref HEAD)

pull() {
	BRANCH=$1
	git checkout $BRANCH
	git pull
	echo
}

pull master

echo
git checkout $ACTIVE_BRANCH
git pull
